# Exercices NumPy 

<span style="color:red">Réalisation de tous les exercices sans utiliser de boucles.</span>
---

In [1]:
import numpy as np

# Configuration de la précision d'affichage
np.set_printoptions(precision=2, suppress=True)
print("NumPy version:", np.__version__)

NumPy version: 2.5.3


## Exercice 1 : Création et restructuration d'un tableau (1D → 2D)

**Objectif :**
1. Créez un vecteur 1D contenant les entiers de 1 à 20.
2. Transformez-le en une matrice 2D de dimensions $4 \times 5$.

In [ ]:
# VOTRE CODE ICI
v = np.arange(1, 21)
m = v.reshape(4, 5)
print(v , '\n')
print(m)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20] 

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


## Exercice 2 : Extraction par masque booléen (1D)

**Objectif :**
Soit un vecteur 1D de 15 nombres aléatoires entre 0 et 50. Extrayez tous les éléments strictement supérieurs à 25 **ET** pairs.

In [ ]:
# VOTRE CODE ICI
v = np.random.randint(0 , 50 , 15)
print(v)

result = v[(v > 25) & (v % 2 == 0)]
print(result)

[33 17 36 34  4 20  1  9 49 15 24  7 38 29 48]
[36 34 38 48]


## Exercice 3 : Inversion et inversion par colonnes (1D et 2D)

**Objectif :**
1. Inversez l'ordre des éléments d'un vecteur 1D de taille 10.
2. Soit une matrice $4 \times 4$, inversez l'ordre de ses colonnes (la dernière colonne devient la première).

In [ ]:
# VOTRE CODE ICI
v = np.arange(1 , 11)
v_inversed = np.flip(v)
# v_inversed = v[::-1]
print(v)
print(v_inversed, '\n')
v_matice = np.arange(1,17)
v_matice = v_matice.reshape(4, 4)
v_matice = np.flip(v_matice , axis=0)
print(v_matice)


[ 1  2  3  4  5  6  7  8  9 10]
[10  9  8  7  6  5  4  3  2  1] 

[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


## Exercice 4 : Statistique par axe (2D)

**Objectif :**
Soit une matrice $5 \times 3$ d'entiers aléatoires entre 1 et 100.
1. Calculez la moyenne globale de la matrice.
2. Calculez la somme des éléments pour chaque **colonne**.
3. Obtenez la valeur maximale pour chaque **ligne**.

In [ ]:
# VOTRE CODE ICI
matrice = np.random.randint(1 , 100 , 15).reshape(5 , 3)
print(matrice)
print(np.mean(matrice))
print(matrice.sum(axis=0))
print(matrice.max(axis=1))

[[95 38 61]
 [42 60 40]
 [88  1 98]
 [58 63 72]
 [42 28  8]]
52.93333333333333
[325 190 279]
[95 60 98 72 42]


## Exercice 5 : Remplacement des valeurs manquantes (1D / 2D)

**Objectif :**
Soit le tableau : `arr = np.array([1.0, 2.0, np.nan, 4.0, np.nan, 6.0])`.
Remplacez toutes les valeurs `NaN` par la moyenne des valeurs non manquantes du tableau.

In [46]:
# VOTRE CODE ICI
arr = np.array([1.0 , 2.0 , np.nan , 4.0 , np.nan , 6.0])
avg = np.nanmean(arr)
arr[np.isnan(arr) ]= avg
print(arr)

[1.   2.   3.25 4.   3.25 6.  ]


## Exercice 6 : Concaténation et empilement (2D)

**Objectif :**
Soit deux matrices $A$ et $B$ de dimensions $3 \times 2$.
1. Empilez-les verticalement pour obtenir une matrice $6 \times 2$.
2. Empilez-les horizontalement pour obtenir une matrice $3 \times 4$.

In [49]:
# VOTRE CODE ICI
A = np.random.randint(1 , 100 , 6).reshape(3 , 2)
B = np.random.randint(1 , 100 , 6).reshape(3 , 2)
v = np.vstack((A , B))
h = np.hstack((A, B))
print(v)
print(h)

[[53 17]
 [11 97]
 [73 30]
 [30 22]
 [85 97]
 [77 17]]
[[53 17 30 22]
 [11 97 85 97]
 [73 30 77 17]]


## Exercice 7 : Recherche d'indices spécifiques (`np.where`) (1D)

**Objectif :**
Soit un vecteur 1D de 12 valeurs réelles. Récupérez les **indices** (et non les valeurs) de tous les éléments compris entre 10 et 20 inclus.

In [52]:
# VOTRE CODE ICI
v = np.random.randint(1 , 30 , 12)
indices = np.where((v >= 10) & (v <= 20))[0]
print(indices)

[ 0  5  7  9 11]


`## Exercice 8 : Calcul de la diagonale et trace (2D)

**Objectif :**
Générez une matrice carrée $4 \times 4$ d'entiers.
1. Extrayez les éléments de la diagonale principale sous forme de vecteur 1D.
2. Calculez la somme de ces éléments (la trace) en utilisant la fonction NumPy dédiée.`

In [54]:
# VOTRE CODE ICI
matrice = np.random.randint(1 , 50 , 16).reshape(4,4)
diagonale = np.diagonal(matrice)
trace = np.trace(matrice)
print(matrice , '\n')
print(diagonale , '\n')
print(trace)

[[44  3 13 40]
 [26 18 20 15]
 [22 37 39 37]
 [29 45 18 19]] 

[44 18 39 19] 

120


## Exercice 9 : Masquage conditionnel & Remplacement rapide (1D)

**Objectif :**
Créez un vecteur 1D de 20 entiers aléatoires entre -10 et 10. Sans utiliser de boucle for ni d'instructions if, remplacez tous les nombres négatifs impairs par leur carré, et tous les nombres positifs pairs par 0.

In [58]:
# VOTRE CODE ICI
vecteur1D = np.random.randint(-10 , 10 , 20)
print(vecteur1D)
vecteur1D[vecteur1D > 0] = 0
vecteur1D[vecteur1D < 0] = vecteur1D[vecteur1D < 0] ** 2
print(vecteur1D)

[  1  -2 -10   4   3  -6   3   9  -5   7  -4  -6   1   2   2  -2   0   6
  -3   8]
[  0   4 100   0   0  36   0   0  25   0  16  36   0   0   0   4   0   0
   9   0]


## Exercice 10 : Extraction par glissement / Fenêtres glissantes (1D)

**Objectif :**
Soit un vecteur 1D $V = [1, 2, 3, 4, 5, 6, 7, 8]$. Générez une matrice 2D représentant toutes les sous-fenêtres glissantes de taille 3 avec un pas (stride) de 1.Résultat attendu :$$\begin{bmatrix} 1 & 2 & 3 \\ 2 & 3 & 4 \\ 3 & 4 & 5 \\ \dots & \dots & \dots \end{bmatrix}$$

In [61]:
# VOTRE CODE ICI
v = np.arange(1 , 9)
vs = np.lib.stride_tricks.sliding_window_view(v, window_shape=3)
print(vs)

[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]]


## Exercice 11 : Extraction des k plus grands éléments par ligne (2D)

**Objectif :**
Soit une matrice 2D de dimensions $6 \times 8$ remplie d'entiers aléatoires. Extrayez, pour chaque ligne, les 3 plus grandes valeurs et leurs indices respectifs, triés par ordre décroissant.

In [70]:
# VOTRE CODE ICI
matrice = np.random.randint(1 , 100 , 48).reshape(6 , 8)
t3indices = np.argsort(matrice , axis=1)[:,-3 :][::-1]
t3valeur = np.take_along_axis(matrice , t3indices , axis=1)
print('indices : -----' , '\n' , t3indices) 
print('valeur : -----' , '\n' , t3valeur) 

indices : ----- 
 [[0 4 1]
 [6 2 3]
 [3 2 4]
 [7 5 1]
 [1 5 7]
 [7 4 0]]
valeur : ----- 
 [[65 59 34]
 [48 39  2]
 [45 26  6]
 [89 84 23]
 [ 1 51 12]
 [62 83 82]]
